#!/usr/bin/env node
/**
 * Extracts the design canvas's shared `:root` custom properties into
 * `design/canvas-tokens.json`, the pinned reference that acceptance
 * criterion C9 checks the primitive token layer against.
 *
 * The canvas itself (`design/redesign-pantallas/`) is deliberately not
 * committed — see design/README.md. This script is what regenerates the
 * committed extraction when the canvas changes, and it refuses to emit
 * anything if the artboards have stopped agreeing on one palette.
 *
 * Usage: node design/extract-tokens.mjs [--check]
 *   --check  exit non-zero if the committed JSON is stale, write nothing
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const CANVAS = join(HERE, 'redesign-pantallas');
const OUT = join(HERE, 'canvas-tokens.json');

if (!existsSync(CANVAS)) {
  console.error(`Canvas not found at ${CANVAS}.`);
  console.error('The canvas is reference-only and is not committed; see design/README.md.');
  process.exit(2);
}

const artboards = readdirSync(CANVAS).filter((f) => f.endsWith('.dc.html')).sort();
if (artboards.length === 0) {
  console.error('No .dc.html artboards found.');
  process.exit(2);
}

/** Pull the `:root{ ... }` block out of one artboard. */
function rootBlock(file) {
  const src = readFileSync(join(CANVAS, file), 'utf8');
  const m = src.match(/:root\{([\s\S]*?)\}/);
  if (!m) throw new Error(`no :root block in ${file}`);
  return m[1];
}

// Every artboard must agree on one palette. If they diverge, there is no
// single source of truth to extract and a human has to look at it.
const blocks = new Map();
for (const file of artboards) {
  const block = rootBlock(file);
  const hash = createHash('sha256').update(block).digest('hex');
  if (!blocks.has(hash)) blocks.set(hash, []);
  blocks.get(hash).push(file);
}
if (blocks.size !== 1) {
  console.error(`Artboards disagree on :root — found ${blocks.size} distinct palettes:`);
  for (const [hash, files] of blocks) {
    console.error(`  ${hash.slice(0, 12)}  ${files.length} artboard(s): ${files.slice(0, 3).join(', ')}${files.length > 3 ? ', …' : ''}`);
  }
  process.exit(1);
}

const [[sourceHash, agreeing]] = [...blocks];
const block = rootBlock(agreeing[0]);

/** Parse `--name:value;` pairs, preserving declaration order. */
const tokens = {};
for (const [, name, value] of block.matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) {
  tokens[name] = value.trim().replace(/\s+/g, ' ');
}

const CATEGORY = [
  [/^(bg|surface)/, 'surface'],
  [/^ink/, 'ink'],
  [/^line/, 'line'],
  [/^(accent|teal|gold|ok|warn)/, 'accent'],
  [/^r(-|$)/, 'radius'],
  [/^shadow/, 'shadow'],
  [/^f[db]$/, 'fontFamily'],
];
const categorised = {};
for (const [name, value] of Object.entries(tokens)) {
  const hit = CATEGORY.find(([re]) => re.test(name));
  const group = hit ? hit[1] : 'uncategorised';
  (categorised[group] ??= {})[name] = value;
}

const uncategorised = Object.keys(categorised.uncategorised ?? {});
if (uncategorised.length > 0) {
  console.error(`Unrecognised custom properties (extend CATEGORY in this script): ${uncategorised.join(', ')}`);
  process.exit(1);
}

const payload = {
  $comment:
    'Generated by design/extract-tokens.mjs from the design canvas. Do not hand-edit — ' +
    'regenerate. This file is the pinned reference for acceptance criterion C9.',
  source: {
    canvas: 'design/redesign-pantallas',
    artboards: agreeing.length,
    rootSha256: sourceHash,
    extractedAt: new Date().toISOString().slice(0, 10),
  },
  tokens: categorised,
};
const serialised = JSON.stringify(payload, null, 2) + '\n';

if (process.argv.includes('--check')) {
  if (!existsSync(OUT)) {
    console.error(`${OUT} is missing. Run: node design/extract-tokens.mjs`);
    process.exit(1);
  }
  const committed = JSON.parse(readFileSync(OUT, 'utf8'));
  if (committed.source?.rootSha256 !== sourceHash) {
    console.error('Canvas has changed since the committed extraction.');
    console.error(`  committed: ${committed.source?.rootSha256?.slice(0, 12)}`);
    console.error(`  canvas:    ${sourceHash.slice(0, 12)}`);
    console.error('Run: node design/extract-tokens.mjs');
    process.exit(1);
  }
  console.log(`canvas-tokens.json is current (${agreeing.length} artboards, one palette).`);
  process.exit(0);
}

writeFileSync(OUT, serialised);
const count = Object.values(categorised).reduce((n, g) => n + Object.keys(g).length, 0);
console.log(`Wrote ${OUT}`);
console.log(`  ${count} tokens from ${agreeing.length} artboards sharing one :root (${sourceHash.slice(0, 12)})`);
